Feature/username validation improvement
BinaryStudioAcademy/bsa-2023-leetwars pull request #103
Opened 2023-09-06 16:47 UTC by Illusion4

2023-09-06 16:53 UTC, Illusion4 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[IMPROVEMENT#3] Validation for the Username field](https://trello.com/c/HH1IIkiY/119-bug42-main-page-the-language-icons-do-not-match-names)

2023-09-06 16:59 UTC, SashaBondarchuk approved these changes

2023-09-06 17:48 UTC, tatianahutii approved these changes

2023-09-07 09:33 UTC, apofis96 requested changes

2023-09-07 09:33 UTC, apofis96 commented on backend/LeetWars.Core/LeetWars.Core.WebAPI/Regaxes/RegexPatterns.cs
> +        public static readonly string LatinOrCyrillicCharactersPattern = "^[a-zA-Zа-яА-Я0-9_]+$";
![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/32576664/64b9de9d-c0a9-4f1b-8abc-46257e6bd1a7)

2023-09-07 10:00 UTC, apofis96 approved these changes

2023-09-07 11:01 UTC, merged