added not-found page
BinaryStudioAcademy/bsa-2023-leetwars pull request #11
Opened 2023-08-21 16:46 UTC by pospyra

![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/68563967/3e6e1c61-5c5b-4b07-ae64-ffed47a0d9f5)

2023-08-21 18:48 UTC, tatianahutii requested changes

2023-08-21 18:48 UTC, tatianahutii commented on frontend/src/app/app-routing.module.ts
> +    { path: '404', component: NotFoundComponent, pathMatch: 'full' },
we don't need this path

2023-08-22 09:13 UTC, tatianahutii requested changes

2023-08-22 09:13 UTC, tatianahutii commented on frontend/src/app/shared/components/not-found/not-found.component.sass
> +  background-color: #1D1E21
All colors should be moved to a color variables

2023-08-22 10:44 UTC, Den313 approved these changes
LGTM

2023-08-22 10:44 UTC, merged