bug/127 like challenge
BinaryStudioAcademy/bsa-2023-leetwars pull request #111
Opened 2023-09-08 13:30 UTC by Limbo2332

I've added addition check for clicking star button and I hope to fix problems with clicking stars on staging. 

Video with working here: https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/pull/110

2023-09-08 13:32 UTC, Limbo2332 commented
Video with bug on staging: 

https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/93576084/b6a3d15e-2955-423e-9016-3dcae152fbe4

2023-09-08 18:00 UTC, bodichka11 approved these changes

2023-09-08 21:08 UTC, Den313 approved these changes

2023-09-11 06:39 UTC, tatianahutii requested changes

2023-09-11 06:39 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.BLL/Services/ChallengeService.cs
> +                if(await GetChallengeStarAsync(challengeStar.Id) is not null)
is it not enough to use Any here (without data and its dependencies loading)?

2023-09-11 06:39 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.BLL/Services/ChallengeService.cs
> +        private async Task<ChallengeStar?> GetChallengeStarAsync(long id)
Almost the same as 129-133, you can pass predicate as a parameter as well

2023-09-11 15:07 UTC, tatianahutii approved these changes

2023-09-11 15:07 UTC, merged