Feature/122-badge-component
BinaryStudioAcademy/bsa-2023-leetwars pull request #114
Opened 2023-09-09 15:45 UTC by Illusion4

https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/88484289/de2d6b54-e585-49b1-91e8-4c76e1585c6b

2023-09-09 15:47 UTC, Illusion4 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Badge component](https://trello.com/c/tREBZA9T/122-badge-component)

2023-09-09 18:33 UTC, AyTee001 approved these changes

2023-09-11 06:30 UTC, tatianahutii requested changes
Need backend to be implemented

2023-09-11 06:30 UTC, tatianahutii commented on frontend/angular.json
> +                            "node_modules/ngx-owl-carousel-o/lib/styles/prebuilt-themes/owl.theme.default.min.css"
it would be better to import them in index.sass

2023-09-11 06:30 UTC, tatianahutii commented on frontend/src/app/shared/components/badge/badge.component.html
> +                <ng-template carouselSlide *ngFor="let item of items; let i = index" [id]="item.badge.src">
do you use index?

2023-09-11 06:30 UTC, tatianahutii commented on frontend/src/app/shared/components/badge/badge.component.ts
> +        };
to the separate method

2023-09-11 06:30 UTC, tatianahutii commented on frontend/src/app/shared/components/badge/badge.component.ts
> +            isActive: index === this.startPosition,
avoid using indexes, use something like order

2023-09-11 16:03 UTC, tatianahutii requested changes

2023-09-11 16:03 UTC, tatianahutii commented on frontend/src/app/shared/components/badge/badge.component.ts
> +        const newString = stringBeforeLastDot + newExtension;
Probably it would be better to create some sort of mapper for all of this badges, as in a future we will have more types and not all of them will follow the same pattern on naming

2023-09-11 16:03 UTC, tatianahutii commented on frontend/src/app/shared/components/badge/badge.component.ts
> +    }
maybe it would be easier just to have some sort of checking in HTML
for example you can show an array (3 elements -1 0 1) and add some kind of checking that an element is first or last)

2023-09-11 17:39 UTC, Illusion4 commented on frontend/src/app/shared/components/badge/badge.component.ts
> +    }
There can be more that 3 elements, but i will try to make that logic simpler

2023-09-11 20:16 UTC, tatianahutii approved these changes

2023-09-12 10:11 UTC, apofis96 approved these changes

2023-09-12 13:30 UTC, merged