Feature/18 sign up page
BinaryStudioAcademy/bsa-2023-leetwars pull request #15
Opened 2023-08-22 11:02 UTC by SashaBondarchuk

https://trello.com/c/3U6LEqQS/18-sign-up-page

![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/56970649/4af9e471-83c3-48a3-bc15-e364109a9215)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/56970649/8d39f73d-47e1-4262-8b09-e8b3a9d7f86c)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/56970649/cc794104-0a5f-4bfc-b2e4-fc2ee6de2544)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/56970649/bd7a9f0d-ea47-4677-b994-fa33b5c6ac91)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/56970649/bb88f4ec-93b0-46d0-b082-de38f8f6787c)

created one module for 2 components
![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/56970649/5110348b-1c89-45cf-b5b7-32bf3eccb306)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/56970649/fe8e8b2d-337d-43a0-aa36-4198b23a0e53)

2023-08-22 11:07 UTC, SashaBondarchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sign Up page](https://trello.com/c/3U6LEqQS/18-sign-up-page)

2023-08-22 12:11 UTC, tatianahutii requested changes

2023-08-22 12:11 UTC, tatianahutii commented on frontend/src/app/app-routing.module.ts
> +    },
Please consolidate your work with developer from Log In page and create one module for 2 components

2023-08-22 12:11 UTC, tatianahutii commented on frontend/src/app/modules/sign-up/sign-up/sign-up.component.sass
> +$extra-large: 1440px
move to a new separate file in frontend/src/styles/.....

2023-08-22 12:11 UTC, tatianahutii commented on frontend/src/app/modules/sign-up/sign-up/sign-up.component.sass
> +    background-color: #222327
move to frontend/src/styles/color-variables.sass

2023-08-22 12:11 UTC, tatianahutii commented on frontend/src/app/modules/sign-up/sign-up/sign-up.component.sass
> +        color: #91919380
the same

2023-08-22 12:11 UTC, tatianahutii commented on frontend/src/styles/color-palette.sass
> +  --color-tangerine:#F5A75F
please move this to frontend/src/styles/color-variables.sass

2023-08-22 18:55 UTC, tatianahutii requested changes
But everything else looks really good

2023-08-22 18:55 UTC, tatianahutii commented on frontend/src/styles/color-variables.sass
> +$medium-grey: #222327
color duplication

2023-08-22 19:48 UTC, tatianahutii approved these changes
LGTM

2023-08-23 08:35 UTC, SashaBondarchuk commented
there was merge conflict with some dublication in color-variables.sass and app routing, so I have resolved it

2023-08-23 08:49 UTC, tatianahutii approved these changes

2023-08-23 10:31 UTC, apofis96 requested changes

2023-08-23 10:31 UTC, apofis96 commented on frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
> +    ngOnInit(): void {
Get rid of onInit here

2023-08-23 16:50 UTC, tatianahutii approved these changes

2023-08-23 16:56 UTC, merged