Feature/124 error interceptor
BinaryStudioAcademy/bsa-2023-leetwars pull request #160
Opened 2023-09-17 11:19 UTC by Limbo2332

https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/93576084/30c0be42-9128-4053-9ddc-81b9334084f5

2023-09-17 11:21 UTC, Limbo2332 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Error interceptor](https://trello.com/c/J2B7tHe0/124-error-interceptor)

2023-09-17 11:51 UTC, SashaBondarchuk requested changes

2023-09-17 11:51 UTC, SashaBondarchuk commented on frontend/src/app/core/services/auth.service.ts
>          );
false can be removed (see line 149)

2023-09-17 11:51 UTC, SashaBondarchuk commented on backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
> +
```suggestion
if (isExistingUserName)
{
    userDto.UserName = userDto.IsWithProvider
        ? await GenerateUniqueUsername(userDto.Email)
        : throw new InvalidUsernameOrPasswordException($"Error: This username is already registered in the system.");
}

```

2023-09-17 12:30 UTC, Limbo2332 commented on frontend/src/app/core/services/auth.service.ts
>          );
Unreal to do, only changed to undefined

2023-09-17 12:32 UTC, SashaBondarchuk approved these changes

2023-09-18 11:57 UTC, tatianahutii approved these changes

2023-09-20 15:13 UTC, Den313 approved these changes

2023-09-20 15:22 UTC, merged