Add user info editor page
BinaryStudioAcademy/bsa-2023-leetwars pull request #167
Opened 2023-09-19 17:14 UTC by Illusion4

https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/88484289/c4ec378d-ca6a-4fcd-bdf5-ac7391c9b5b0

2023-09-19 17:22 UTC, Illusion4 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Edit user info component](https://trello.com/c/7sNYIAFT/134-edit-user-info-component)

2023-09-20 14:37 UTC, bodichka11 approved these changes

2023-09-20 14:58 UTC, tatianahutii requested changes

2023-09-20 14:58 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
> +        if(image is null)
```suggestion
        if (image is null)

```

2023-09-20 14:58 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
> +        currentUser!.Email = userInfoDto.Email!;
please avoid using !

2023-09-20 14:58 UTC, tatianahutii commented on backend/LeetWars.Core/Dockerfile
> +
do we really need this? we can store all secret data in env variables, not secret in appsettings

2023-09-20 14:58 UTC, tatianahutii commented on frontend/src/app/modules/user/user-info-editor/user-info-editor.component.ts
> +            this.avatarPreview = this.user?.imagePath ?? '/assets/images/default-profile-img.jpg';
magic string

2023-09-20 14:58 UTC, tatianahutii commented on frontend/src/app/modules/user/user-info-editor/user-info-editor.component.ts
> +        const file = target.files[0];
```suggestion
        const file =  target.files && target.files[0];
         if (!file ) {
            return;
        }
```

2023-09-20 14:58 UTC, tatianahutii commented on frontend/src/app/shared/components/header/header.component.ts
> +        this.authService.currentUser$.pipe(takeUntil(this.destroy$))
you can inherit BaseComponent

2023-09-20 14:58 UTC, tatianahutii commented on frontend/src/app/shared/models/user/edit-user-info.ts
> +export interface EditUserInfo {
```suggestion
export interface IEditUserInfo {

```

2023-09-20 14:58 UTC, tatianahutii commented on frontend/src/app/shared/models/user/user-avatar.ts
> +export interface UserAvatar {
```suggestion
export interface IUserAvatar {

```

2023-09-20 16:45 UTC, tatianahutii requested changes

2023-09-20 16:45 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
> +        currentUser.UserName = userInfoDto.Username;
auto mapper?

2023-09-20 16:45 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
> +        var currentUser = await _context.Users.FirstOrDefaultAsync(x => x.Uid == _userGetter.CurrentUserId)
Don't we have our custom exceptions for this case?

2023-09-20 16:45 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.Common/DTO/User/UserFullDto.cs
> +        public string? ImagePath { get; set; }
is it duplication? we have ImagePath in IDtoWithImage as well

2023-09-20 16:45 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.Common/DTO/User/UserDto.cs
> +    public class UserDto : Entity<long>, IDtoWithImage
the same here

2023-09-20 16:45 UTC, tatianahutii commented on frontend/src/app/modules/user/user-info-editor/user-info-editor.component.sass
> +.editUserInfoForm
use the same style for class names

2023-09-20 21:08 UTC, tatianahutii approved these changes

2023-09-21 12:08 UTC, apofis96 approved these changes

2023-09-21 12:09 UTC, merged