Feature/7-Basic-RabbitMQ
BinaryStudioAcademy/bsa-2023-leetwars pull request #17
Opened 2023-08-22 12:32 UTC by bodichka11

To send message call post endpoint: /sendmessage/(your message)

2023-08-22 12:35 UTC, bodichka11 commented
https://trello.com/c/IogGP1Ud

2023-08-22 13:50 UTC, tatianahutii requested changes

2023-08-22 13:50 UTC, tatianahutii commented on backend/LeetWars.RabbitMQ/Program.cs
> +app.MapGet("/", () => "Hello World!");
please delete test endpoints

2023-08-22 13:50 UTC, tatianahutii commented on backend/LeetWars.RabbitMQ/Dockerfile
> +EXPOSE 80
We do not need this. As Rabbit should be a separate project that will be attached to either service (not a separate service)

2023-08-22 14:47 UTC, bodichka11 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Basic RabbitMQ](https://trello.com/c/IogGP1Ud/7-basic-rabbitmq)

2023-08-23 12:56 UTC, tatianahutii approved these changes

2023-08-23 13:48 UTC, merged