added a message that data will be lost if the user leaves or reload t…
BinaryStudioAcademy/bsa-2023-leetwars pull request #186
Opened 2023-09-22 16:34 UTC by pospyra

https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/68563967/a0914f99-e67f-445a-93e3-68e77d35b0bc

![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/68563967/d5f77df0-f7b8-4b7f-b40c-285ff1363b52)
(default text there)

2023-09-22 16:53 UTC, AyTee001 approved these changes

2023-09-24 18:08 UTC, tatianahutii approved these changes

2023-09-24 18:08 UTC, tatianahutii commented on frontend/src/app/core/guards/unsaved-changes.guard.ts
> +            if (component.unsavedChanges) {
```suggestion
            if (!component.unsavedChanges) {
                resolve(true);
            }
```

2023-09-24 18:08 UTC, tatianahutii commented on frontend/src/app/core/guards/unsaved-changes.guard.ts
> +                ];
to a separate method

2023-09-24 18:08 UTC, tatianahutii commented on frontend/src/app/core/guards/unsaved-changes.guard.ts
> +            if (component.unsavedChanges) {
or even better to use ternary operator here

2023-09-24 18:09 UTC, tatianahutii requested changes
See the previous comments

2023-09-26 07:25 UTC, tatianahutii requested changes

2023-09-26 07:25 UTC, tatianahutii commented on frontend/src/app/core/guards/unsaved-changes.guard.ts
> +        });
```suggestion
        return component.unsavedChanges
            ? this.showConfirmationModal()
           :  Promise.resolve(true);
        });
```

2023-09-26 09:48 UTC, tatianahutii approved these changes

2023-09-26 09:49 UTC, merged