changed styles on header
BinaryStudioAcademy/bsa-2023-leetwars pull request #188
Opened 2023-09-22 17:15 UTC by pospyra

![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/68563967/63ba194e-18e2-4e36-9cd4-dc955c0461a9)

2023-09-22 19:34 UTC, SashaBondarchuk approved these changes

2023-09-24 18:33 UTC, tatianahutii requested changes
Gap between bell and user icon should be less

2023-09-24 19:31 UTC, pospyra commented
> Gap between bell and user icon should be less

![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/68563967/de28c591-1ad2-4183-8e25-e9fa12c5eb79)

2023-09-26 09:48 UTC, tatianahutii approved these changes

2023-09-26 09:48 UTC, merged