Fixed display of a problem when selecting “Select language...”
BinaryStudioAcademy/bsa-2023-leetwars pull request #189
Opened 2023-09-22 18:17 UTC by pospyra

![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/68563967/e9de41eb-83cc-4dfa-bedd-f1e2f8b474dd)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/68563967/b6fc4aaa-b0e8-49f3-9afb-30cddc8dcfcb)

https://trello.com/c/EhvjYs1G/205-bug79-main-page-the-challenge-is-absent-in-the-suggested-challenge-block

2023-09-23 12:04 UTC, Slayrak approved these changes

2023-09-24 18:35 UTC, tatianahutii requested changes

2023-09-24 18:35 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.BLL/Services/ChallengeService.cs
> +            if (settings.LanguageId is not 0)
this is not good that LanguageId can be 0. it should be null or number

2023-09-26 09:47 UTC, tatianahutii approved these changes

2023-09-26 09:47 UTC, merged