Feature/201 other user profile
BinaryStudioAcademy/bsa-2023-leetwars pull request #198
Opened 2023-09-26 14:47 UTC by Slayrak

https://trello.com/c/SsEQIEvh/201-other-user-profile

2023-09-26 16:18 UTC, AyTee001 approved these changes

2023-09-26 19:51 UTC, tatianahutii requested changes

2023-09-26 19:51 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IUserService.cs
> +    public Task<UserFullDto> GetUserByNickname(string nickname);
it would be better to load UserId to leaderboard and use existed methods for loading user by Id

2023-09-27 15:17 UTC, tatianahutii requested changes

2023-09-27 15:17 UTC, tatianahutii commented on frontend/src/app/modules/user/user-profile/user-profile.component.ts
> +                }
```suggestion
                    this.isCurrentUser = !userId || this.currentUser?.id === userId;
                    const curentUserId = this.isCurrentUser  ? this.user.id : userId;
                    this.getUserInfo(curentUserId );
                    this.getUserChallenges(curentUserId );
```

2023-09-27 18:45 UTC, tatianahutii approved these changes

2023-09-27 19:42 UTC, merged