Feature/181 generate challenge ai
BinaryStudioAcademy/bsa-2023-leetwars pull request #199
Opened 2023-09-26 20:43 UTC by bodichka11

2023-09-27 20:10 UTC, pospyra commented on backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/Controllers/AnalyzeCodeController.cs
> +{
[Route("[controller]")]
 and delete route from [HttpPost]

2023-09-27 20:10 UTC, pospyra commented on backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/Controllers/ChallengeGenerateController.cs
> +    [ApiController]
the same

2023-09-27 20:10 UTC, pospyra commented on backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/Services/ChallengeGenerator.cs
> +
maybe mapper?

2023-09-28 12:16 UTC, bodichka11 commented
https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/113329862/961e04d2-41c6-47a7-aa70-80b880009188

https://trello.com/c/hOkdqz0N/181-generate-challenge-ai

2023-09-28 12:16 UTC, pospyra approved these changes

2023-09-28 14:05 UTC, tatianahutii commented
@bodichka11 please rework modal windows to our common style

2023-09-28 14:41 UTC, tatianahutii requested changes

2023-09-28 14:41 UTC, tatianahutii commented on backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/Controllers/AnalyzeCodeController.cs
> +
empty lines

2023-09-28 14:41 UTC, tatianahutii commented on backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/MappingProfiles/ChallengeGeneratorProfile.cs
> +                .ForMember(dest => dest.ExampleTestCases, opt => opt.MapFrom(src => src.TestsSubset));
you dont need to defind map for all properties with the same name

and you can use .ReverseMap()

2023-09-28 14:41 UTC, tatianahutii commented on backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/OpenAISettings/OpenAiSettings.cs
> +            if(challengeGenerateRequestDto.Tags == null)
```suggestion
            if (challengeGenerateRequestDto.Tags is null) 
```

2023-09-28 14:41 UTC, tatianahutii commented on backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/Services/ChallengeGenerator.cs
> +            }
```suggestion
            var challengeResponse = JsonConvert.DeserializeObject<OpenAiChallengeGenerateResponseDto>(response) ??  throw new NotFoundException(nameof(challengeResponse));
```

2023-09-28 14:41 UTC, tatianahutii commented on backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/Services/ChallengeGenerator.cs
> +            _mapper.Map(challengeGenerateRequest, challengeGenerateResponseDto);
why do we need 2 maps?

2023-09-28 14:41 UTC, tatianahutii commented on backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/Services/CompletionService.cs
> +
empty line

2023-09-28 14:41 UTC, tatianahutii commented on backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/appsettings.json
> +
empty line

2023-09-28 14:41 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/ChallengeController.cs
> +
new empty spaces

2023-09-28 14:41 UTC, tatianahutii commented on frontend/nginx.conf
> +    location /codeanalyzer {
please check upstream as well

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.ts
> +        }
not in consltucroe
and use spread operator for defending properties

and why || 0? default values should be null or underfined

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.ts
> +    public onStepClick(step: ChallengeStep) {
we dont need public here

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/modules/main/main-page/main-page.component.html
> -<app-arrow-up [onScrollEvent]="scrollEventSubject.asObservable()"></app-arrow-up>
why did you delete this?

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/modules/main/main-page/main-page.component.ts
> +                    modalRef.componentInstance.updateChallengeGenerateRequest();
why this method is in modal?

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/modules/main/main-page/main-page.component.ts
> +        });
see the previous comment

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/modules/main/main-page/main-page.component.ts
> +                    this.spinnerService.show();
why spinner show 2 times?

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/modules/main/main-page/main-page.component.ts
> +                            myComplexObject: response,
not a good name of state data

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/modules/main/main-page/main-page.component.ts
> +            });
where are you hiding the spinner?

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/shared/components/describe-question/describe-question/describe-question.component.sass
> +.mr-24px
different indent
should be tab

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/shared/components/describe-question/describe-question/describe-question.component.ts
> +import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
I beliave this should be a part of challenge module, not shared

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/shared/components/describe-question/describe-question/describe-question.component.ts
> +    @Output() challengeGenerateRequestChange = new EventEmitter<IChallengeGenerateRequest>();
all inputs together

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/shared/components/describe-question/describe-question/describe-question.component.ts
> +        const selectedLanguage: ILanguage | undefined = this.languages.find(
```suggestion
        const selectedLanguage = this.languages.find(
```

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/shared/components/describe-question/describe-question/describe-question.component.ts
> +        };
spread operator

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/shared/components/describe-question/describe-question/describe-question.component.ts
> +    public CategoryType = CategoryType;
properties all together

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/shared/components/describe-question/describe-question/describe-question.component.ts
> +    public onLanguageChanged(selectedItem: IDropdownItem) {
you dont need public
please delete everywhere

2023-09-28 14:41 UTC, tatianahutii commented on frontend/src/app/shared/components/describe-question/describe-question/describe-question.component.ts
> +        }
duplications

2023-09-29 09:39 UTC, tatianahutii approved these changes

2023-09-29 09:45 UTC, merged