added markdown preview
BinaryStudioAcademy/bsa-2023-leetwars pull request #206
Opened 2023-09-28 11:38 UTC by SashaBondarchuk

https://trello.com/c/DfHaAokq/209-bug83-main-page-the-challenge-description-is-absent-in-the-suggested-challenge-block

![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/56970649/880fdc9d-22ae-4813-8f30-69f40fb8b95a)

![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/56970649/3af675c4-feba-4efa-9e7f-880bc78fcf7f)

2023-09-28 12:09 UTC, SashaBondarchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG#92] [Challenge page] When the challenge page opens, the header is half visible](https://trello.com/c/I6VExyBM/226-bug92-challenge-page-when-the-challenge-page-opens-the-header-is-half-visible)

2023-09-28 13:36 UTC, bodichka11 approved these changes

2023-09-28 17:18 UTC, SashaBondarchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG#110] [Editor challenge page] The page does not open correctly](https://trello.com/c/KbTgocEa/251-bug110-editor-challenge-page-the-page-does-not-open-correctly)

2023-09-28 17:18 UTC, SashaBondarchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG#99] [Profile page] The main info block changes the size according to the username](https://trello.com/c/HtzPFYcu/236-bug99-profile-page-the-main-info-block-changes-the-size-according-to-the-username)

2023-09-28 19:32 UTC, SashaBondarchuk commented
https://trello.com/c/KbTgocEa/251-bug110-editor-challenge-page-the-page-does-not-open-correctly

https://trello.com/c/HtzPFYcu/236-bug99-profile-page-the-main-info-block-changes-the-size-according-to-the-username

2023-09-28 19:38 UTC, tatianahutii requested changes

2023-09-28 19:38 UTC, tatianahutii commented on frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.ts
> +        window.scrollTo({ top: 0, behavior: 'smooth' });
I believe this is more as a workaround as fixing the core root cause

2023-09-29 09:16 UTC, SashaBondarchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG#89] [Auth] Refresh token functionality does not work](https://trello.com/c/wZ9cayDg/215-bug89-auth-refresh-token-functionality-does-not-work)

2023-09-29 09:16 UTC, SashaBondarchuk commented
![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/56970649/0a819939-70b1-40e7-9986-e245798d64ac)

2023-09-29 09:43 UTC, tatianahutii requested changes

2023-09-29 09:43 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +                console.error('Error refreshing Firebase token:', error);
please delete all console.error

2023-09-29 09:43 UTC, tatianahutii commented on frontend/src/app/shared/components/header/header.component.ts
> +                    this.toastrService.showError('Server connection error');
please show error message from our backend

2023-09-29 09:43 UTC, tatianahutii commented on frontend/src/app/shared/components/header/header.component.ts
> +                    this.toastrService.showError('Server connection error');
the same

2023-09-29 10:14 UTC, SashaBondarchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG#125] [Profile page] When the user has a long name, the profile page will not adapt](https://trello.com/c/3zaTpe0d/277-bug125-profile-page-when-the-user-has-a-long-name-the-profile-page-will-not-adapt)

2023-09-29 13:58 UTC, tatianahutii approved these changes

2023-09-29 14:14 UTC, merged

2023-09-29 14:18 UTC, SashaBondarchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG#121] [Notifications]The notification's menu doesn't close and counter doesn't disappear after clicking on the notification](https://trello.com/c/2Emdf2F0/258-bug121-notificationsthe-notifications-menu-doesnt-close-and-counter-doesnt-disappear-after-clicking-on-the-notification)