Feature/50 queue core & builder
BinaryStudioAcademy/bsa-2023-leetwars pull request #39
Opened 2023-08-25 16:11 UTC by Limbo2332

2023-08-25 16:12 UTC, Limbo2332 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Queue Core&Builder](https://trello.com/c/rhgpAHWk/50-queue-corebuilder)

2023-08-25 16:20 UTC, Limbo2332 commented
Maybe, I need to make it by services, especially, setting connection and consumer/producer setting, but it needs from me to change LeetWars.RabbitMQ project. Thanks

2023-08-25 18:27 UTC, Limbo2332 commented
I must get rid of dispose implementation because rabbit doesn't want to send message for the next time (I tried all life cycles)

2023-08-28 06:37 UTC, tatianahutii requested changes

2023-08-28 06:37 UTC, tatianahutii commented on backend/LeetWars.Builder/appsettings.json
> +  "RabbitURI": "amqp://guest:guest@rabbitmq:5672",
are you sure this will work locally?

2023-08-28 06:37 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.BLL/Services/ConsumeMessages.cs
> +                //TODO: do something with message
please delete all todo comments

2023-08-28 06:37 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.WebAPI/Program.cs
> +
to a separate extension method

2023-08-28 06:37 UTC, tatianahutii commented on backend/LeetWars.RabbitMQ/Services/ConsumerService.cs
> +                //_connection.Dispose();
why did you comment this?

2023-08-28 06:37 UTC, tatianahutii commented on backend/LeetWars.RabbitMQ/Services/ProducerService.cs
> +                //_connection.Dispose();
the same

2023-08-29 10:10 UTC, tatianahutii approved these changes

2023-08-29 13:39 UTC, apofis96 approved these changes

2023-08-29 13:40 UTC, merged