Feature/solved problem component
BinaryStudioAcademy/bsa-2023-leetwars pull request #40
Opened 2023-08-26 15:26 UTC by bodichka11

https://trello.com/c/T6zDAumk/40-profile-solved-problem-component

2023-08-28 06:46 UTC, tatianahutii requested changes

2023-08-28 06:46 UTC, tatianahutii commented on frontend/src/app/modules/landing/landing.module.ts
> +    imports: [SharedModule, LandingRoutingModule, UserModule],
why do we need UserProfile in Landing module?

2023-08-28 06:46 UTC, tatianahutii commented on frontend/src/app/shared/components/pie-chart/pie-chart.component.sass
> +
remove unnecessary empty lines (everywhere)

2023-08-28 06:46 UTC, tatianahutii commented on frontend/src/app/shared/components/pie-chart/pie-chart.component.ts
> +
```suggestion
    @Input() currentNumber: number;

    @Input() totalNumber: number;

```

2023-08-28 06:46 UTC, tatianahutii commented on frontend/src/app/shared/components/pie-chart/pie-chart.component.ts
> +        Object.assign(this, { this: this.single });
why do we need this?

2023-08-28 15:21 UTC, tatianahutii requested changes

2023-08-28 15:21 UTC, tatianahutii commented on frontend/src/app/modules/user/solved-problem/solved-problem.component.sass
> +    background-color: #2CBB5D40
still a lot of colors need to be replaces with variables

2023-08-28 15:21 UTC, tatianahutii commented on frontend/src/app/shared/components/pie-chart/pie-chart.component.sass
> +
delete empty lines

2023-08-28 15:21 UTC, tatianahutii commented on frontend/src/app/shared/components/pie-chart/pie-chart.component.ts
> +            domain: [this.activeColor, '#F0F0F0'],
to a separate (shared) file with colors

2023-08-29 07:06 UTC, tatianahutii requested changes

2023-08-29 07:06 UTC, tatianahutii commented on frontend/src/app/modules/user/solved-problem/solved-problem.component.sass
> +
you can move all color variables to one file "color-variables"

2023-08-29 07:06 UTC, tatianahutii commented on frontend/src/app/modules/user/solved-problem/solved-problem.component.ts
> +    @Input() pieChartActiveColor: string = '#FFA116';
create a separate fi;e for all color constants that we use across components

2023-08-29 07:06 UTC, tatianahutii commented on frontend/src/app/modules/user/solved-problem/solved-problem.component.ts
> +    @Input() pieChartActiveColor: string = '#FFA116';
and use them everywhere

2023-08-29 07:06 UTC, tatianahutii commented on frontend/src/app/shared/styles/progressbar-colors.sass
> +$crimson-red:#EF474340
this will cause warnings. Add white space between name and value

2023-08-29 11:48 UTC, tatianahutii approved these changes

2023-08-29 12:08 UTC, apofis96 requested changes

2023-08-29 12:08 UTC, apofis96 commented on frontend/src/app/modules/user/solved-problem/solved-problem.component.sass
> +
dont use ::ng-deep without :host

2023-08-29 13:33 UTC, apofis96 approved these changes

2023-08-29 13:57 UTC, merged