feature/55-emailer-service
BinaryStudioAcademy/bsa-2023-leetwars pull request #43
Opened 2023-08-28 13:25 UTC by bodichka11

https://trello.com/c/wJt75kPb/55-emailer-service

2023-08-28 15:24 UTC, tatianahutii requested changes

2023-08-29 07:09 UTC, tatianahutii requested changes

2023-08-29 07:09 UTC, tatianahutii commented on docker-compose.apps.prod.yml
> +            ASPNETCORE_ENVIRONMENT: 'Development'
Production mode

2023-08-29 10:12 UTC, tatianahutii approved these changes

2023-08-29 12:08 UTC, apofis96 approved these changes

2023-08-29 12:13 UTC, merged