[BUG#1] [Header]  header fix
BinaryStudioAcademy/bsa-2023-leetwars pull request #44
Opened 2023-08-29 09:22 UTC by pashamed

https://trello.com/c/ALUeTqFT/62-bug1-header-the-header-does-not-match-the-design
![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/3277948/ea964ef1-b1fe-4fef-8655-351e7b68fc89)

2023-08-29 09:26 UTC, pashamed commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG#1] [Header] The Header does not match the design](https://trello.com/c/ALUeTqFT/62-bug1-header-the-header-does-not-match-the-design)

2023-08-29 09:53 UTC, tatianahutii requested changes

2023-08-29 09:53 UTC, tatianahutii commented on frontend/src/app/modules/main/main-page/main-page.component.html
> +<app-header></app-header>
header should be not only in the main page

2023-08-29 10:15 UTC, tatianahutii requested changes

2023-08-29 10:15 UTC, tatianahutii commented on frontend/src/app/modules/login/log-in-page/log-in-page.component.html
> +<app-header></app-header>
header should be added once, for all pages

2023-08-29 11:28 UTC, pashamed reviewed
adde header globaly

2023-08-30 13:40 UTC, tatianahutii requested changes

2023-08-30 13:40 UTC, tatianahutii commented on frontend/src/app/app.component.ts
> +    template: '<app-header></app-header><app-loading-spinner></app-loading-spinner><router-outlet></router-outlet>',
not here=)

2023-08-30 14:49 UTC, pashamed commented on frontend/src/app/app.component.ts
> +    template: '<app-header></app-header><app-loading-spinner></app-loading-spinner><router-outlet></router-outlet>',
hope this is the right place =)

2023-08-31 08:33 UTC, apofis96 requested changes
Hint: header should be be added only once before router outlet

2023-08-31 15:16 UTC, tatianahutii approved these changes

2023-08-31 15:16 UTC, merged