Feature/45 general validation
BinaryStudioAcademy/bsa-2023-leetwars pull request #50
Opened 2023-08-29 17:14 UTC by pospyra

2023-08-29 20:04 UTC, tatianahutii requested changes

2023-08-29 20:04 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
> +        return isExistingEmail;
you can use just AnyAsync instead of all these lines

2023-08-29 20:04 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.WebAPI/Validators/User/UserRegisterDTOValidator.cs
> +            return !string.IsNullOrWhiteSpace(userName) && Regex.IsMatch(userName, "^[A-Za-z -]+$", RegexOptions.None, TimeSpan.FromMilliseconds(100));
regex to a separate file where we will store all regeses

2023-08-29 20:04 UTC, tatianahutii commented on frontend/src/app/modules/login/log-in-page/log-in-page.component.ts
> +                        .subscribe(() => {
subscribe in subscribe is not a good idea, use RxJS

2023-08-29 20:04 UTC, tatianahutii commented on frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
> +                        .subscribe(() => {
see the previous comments

2023-08-29 20:04 UTC, tatianahutii commented on frontend/src/app/shared/components/custom-input/custom-input.component.ts
> +    onChange: any = () => {};
please do not use any

2023-08-29 20:04 UTC, tatianahutii commented on frontend/src/app/shared/components/custom-input/custom-input.component.ts
> +    onChange: any = () => {};
everywhere

2023-08-30 13:28 UTC, tatianahutii commented on frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
> +            Validators.pattern('^[A-Za-z\\s-]+$'),
separate file for regex

2023-08-30 13:29 UTC, tatianahutii commented on frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
> +        ).subscribe();
2 subscribes
and need to refactor, it is not redable

2023-08-31 14:48 UTC, apofis96 requested changes

2023-08-31 14:48 UTC, apofis96 commented on backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
> +        bool isExistingEmail = await _context.Users.AnyAsync(u => u.Email == email);
Is the "mail@example.com" and "Mail@example.com" different emails?)

2023-08-31 18:17 UTC, tatianahutii approved these changes

2023-08-31 18:52 UTC, merged