Feature/49 finalize user profile
BinaryStudioAcademy/bsa-2023-leetwars pull request #71
Opened 2023-08-31 18:03 UTC by pashamed

https://trello.com/c/55OdZk0v/49-finalize-user-profile
![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/3277948/0eb3a76a-825b-4011-939e-89c1fde86a6b)

Still solved problems graph is not done yet

2023-08-31 18:24 UTC, pashamed commented
still have to retrieve data for the solved problems pie chart, and implement only auth user access

2023-08-31 18:30 UTC, tatianahutii requested changes
The place of elements from screenshots is not the same as in Figma
[https://user-images.githubusercontent.com/3277948/264769137-99401ec2-7303-4c83-bed9-154afea585ed.png](url)

2023-08-31 18:30 UTC, tatianahutii commented on frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.ts
> +    private getLastWeekDates() {
move to the shared data hlper

2023-08-31 18:30 UTC, tatianahutii commented on frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.ts
> +    private getLastWeekDates() {
and you can use moment library (we already have it) instead of this

2023-08-31 18:30 UTC, tatianahutii commented on frontend/src/app/modules/user/user-profile/user-profile.component.ts
> +            // eslint-disable-next-line function-paren-newline
do not use eslint-disable-next-line

2023-08-31 18:30 UTC, tatianahutii commented on frontend/src/assets/images/submissions.png
please delete this and just leave empty space

2023-08-31 18:33 UTC, pashamed commented on frontend/package.json
> +        "start": "ng serve --host=127.0.0.1",
it didnt allow me to debug, defining explicitly solved the problem

2023-08-31 18:41 UTC, pashamed commented on frontend/src/app/modules/user/submissions-chart/submissions-chart.component.scss
> +.chart-month-title {
not me, merged it from dev, but will remove it

2023-08-31 18:43 UTC, pashamed commented on frontend/src/app/modules/user/submissions-chart/submissions-chart.component.scss
> +.chart-month-title {
not me, merged it from dev, but will do it

2023-08-31 20:09 UTC, pashamed commented
![image](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/3277948/99401ec2-7303-4c83-bed9-154afea585ed)

2023-08-31 20:49 UTC, pashamed commented on frontend/package-lock.json
deleted

2023-09-01 06:44 UTC, pashamed reviewed
removed picture, added a div box instead

2023-09-01 07:21 UTC, pashamed commented
> The place of elements from screenshots is not the same as in Figma

removed picture, added a div box instead

2023-09-04 09:37 UTC, apofis96 requested changes

2023-09-04 09:37 UTC, apofis96 commented on backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/UsersController.cs
> +    [AllowAnonymous]
why we allow this for anonymouse?

2023-09-07 19:18 UTC, bodichka11 commented
![Screenshot 2023-09-07 221713](https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/113329862/d2f48650-9bbc-42b0-aa2a-56c1004f762b)

2023-09-07 22:38 UTC, Limbo2332 requested changes
Entities name changes look good, but it can lead to major problems for other pull requests.

2023-09-07 22:38 UTC, Limbo2332 commented on frontend/src/app/core/services/user.service.ts
> +        return this.httpService.getRequest<IUserFull>(`/users/${id}`);
/users is duplicated, try using baseUrl

2023-09-07 22:38 UTC, Limbo2332 commented on frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.sass
> +    border:  1px solid black
use color-variables

2023-09-07 22:38 UTC, Limbo2332 commented on frontend/src/app/core/services/auth.service.ts
> +        return this.getUserToken() ? this.getUserInfo() : null;
I think this method cannot be used to get user. I'd recommend create new function, for example, getUser

2023-09-07 22:38 UTC, Limbo2332 commented on frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.ts
> +    public userRank = '';
these variables not longer needed

2023-09-08 10:09 UTC, Limbo2332 approved these changes

2023-09-08 10:11 UTC, tatianahutii approved these changes

2023-09-08 10:13 UTC, merged