feature/56-solution-page-new
BinaryStudioAcademy/bsa-2023-leetwars pull request #77
Opened 2023-08-31 22:43 UTC by bodichka11

2023-09-01 07:41 UTC, bodichka11 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create Challenges (Solution page)](https://trello.com/c/9JhfabmL/56-create-challenges-solution-page)

2023-09-04 09:25 UTC, apofis96 requested changes

2023-09-04 09:25 UTC, apofis96 commented on frontend/src/app/modules/challenges/solution-page/solution-page.component.html
> +                        <ng-containt ngbTooltip="You see, I show up on click!" style="gap: 9px;">
why inline style?

2023-09-04 09:25 UTC, apofis96 commented on frontend/src/styles/color-variables.sass
> +$gray-smoke:#EBEBEB
space missed

2023-09-05 10:36 UTC, apofis96 approved these changes

2023-09-05 11:03 UTC, tatianahutii approved these changes

2023-09-05 11:03 UTC, merged