hotfix/login-error
BinaryStudioAcademy/bsa-2023-leetwars pull request #78
Opened 2023-09-01 06:55 UTC by Illusion4

2023-09-01 15:20 UTC, tatianahutii requested changes

2023-09-01 15:20 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/UsersController.cs
> +        var uid = HttpContext.User.Claims.First(i => i.Type == ClaimTypes.NameIdentifier).Value;
any logic in controllers

2023-09-01 15:20 UTC, tatianahutii commented on backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/UsersController.cs
> +        var uid = HttpContext.User.Claims.First(i => i.Type == ClaimTypes.NameIdentifier).Value;
and we have service for this

2023-09-04 09:18 UTC, apofis96 requested changes

2023-09-04 09:18 UTC, apofis96 commented on backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
> +        }
can be simplified with `??` construction
And also use `is null` comparison in the future

2023-09-04 09:57 UTC, apofis96 approved these changes

2023-09-04 10:55 UTC, tatianahutii approved these changes

2023-09-04 10:55 UTC, merged