Bug/36 selected tag is all
BinaryStudioAcademy/bsa-2023-leetwars pull request #95
Opened 2023-09-05 19:32 UTC by Limbo2332

https://github.com/BinaryStudioAcademy/bsa-2023-leetwars/assets/93576084/501b85b1-57bc-4963-828a-9b139f2c740b

2023-09-05 19:38 UTC, Limbo2332 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG#36] [Main page] When the All tag is selected, other tags are available for selection](https://trello.com/c/leaj98hG/110-bug36-main-page-when-the-all-tag-is-selected-other-tags-are-available-for-selection)

2023-09-06 07:52 UTC, tatianahutii requested changes

2023-09-06 07:52 UTC, tatianahutii commented on frontend/src/app/shared/components/dropdown-select/dropdown-select.component.ts
> +    public ngOnChanges(changes: SimpleChanges): void {
```suggestion
    public ngOnChanges({ selectedItem }: SimpleChanges): void {
```

2023-09-06 07:52 UTC, tatianahutii commented on frontend/src/app/shared/components/dropdown-select/dropdown-select.component.ts
> +        this.SelectedItemsChanged.emit(this.selectedItems);
```suggestion
        this.selectedItemsChanged.emit(this.selectedItems);
```

2023-09-06 12:58 UTC, AyTee001 approved these changes

2023-09-06 13:01 UTC, tatianahutii approved these changes

2023-09-06 13:13 UTC, Den313 approved these changes

2023-09-06 13:13 UTC, merged